// Attributes that need to be renamed
export const MAPPED_ATTRIBUTES = new Map<string, string>([
  ['className', 'class'],
  ['htmlFor', 'for'],
  ['glyphName', 'glyph-name'],
  ['glyphOrientationHorizontal', 'glyph-orientation-horizontal'],
  ['glyphOrientationVertical', 'glyph-orientation-vertical'],
  ['markerEnd', 'marker-end'],
  ['markerMid', 'marker-mid'],
  ['markerStart', 'marker-start'],
  ['textAnchor', 'text-anchor'],
  ['textDecoration', 'text-decoration'],
  ['textRendering', 'text-rendering'],
]);

// Components replaced because of solid handling of web components
const REPLACED_COMPAT_SET = new Set(['mjx-container', 'mjx-tool', 'mjx-tip', 'mjx-status']);
export const REPLACED_COMPAT = new Map<string, string>(
  [...REPLACED_COMPAT_SET].map((key) => [key, key.replace(/-/g, '_')])
);

// Attributes that need to be converted to lowercase
const LOWERCASE_ATTRIBUTES_SET = new Set([
  'autoComplete',
  'autoFocus',
  'allowFullScreen',
  'contentEditable',
  'formNoValidate',
  'isMap',
  'noModule',
  'noValidate',
  'playsInline',
  'readOnly',
  'tabIndex',
]);
export const LOWERCASE_ATTRIBUTES = new Map<string, string>(
  [...LOWERCASE_ATTRIBUTES_SET].map((attribute) => [attribute, attribute.toLowerCase()])
);

export const CSS_PROPERTIES = new Set([
  'accent',
  'align',
  'animation',
  'aspect',
  'backdrop',
  'backface',
  'background',
  'block',
  'border',
  'box',
  'break',
  'caption',
  'caret',
  'clip',
  'column',
  'content',
  'counter',
  'empty',
  'flex',
  'font',
  'forced',
  'grid',
  'hanging',
  'image',
  'initial',
  'inline',
  'inset',
  'justify',
  'letter',
  'line',
  'list',
  'margin',
  'mask',
  'max',
  'mix',
  'object',
  'offset',
  'outline',
  'overflow',
  'overscroll',
  'padding',
  'page',
  'place',
  'pointer',
  'row',
  'ruby',
  'scroll',
  'scrollbar',
  'shape',
  'tab',
  'table',
  'text',
  'touch',
  'transform',
  'unicode',
  'user',
  'vertical',
  'white',
  'will',
  'word',
  'writing',
  'z',
]);

export const SVG_ATTRIBUTES = new Set([
  'accent',
  'arabic',
  'baseline',
  'cap',
  'clip',
  'color',
  'dominant',
  'enable',
  'fill',
  'flood',
  'font',
  'horiz',
  'image',
  'letter',
  'lightning',
  'mask',
  'overline',
  'paint',
  'pointer',
  'rendering',
  'shape',
  'stop',
  'strikethrough',
  'stroke',
  'transform',
  'underline',
  'v',
  'vector',
  'vert',
  'x',
]);
